import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://cellma4testing.riomed.com/cellmaUser/login');
  await page.getByTestId('Username').click();
  await page.getByTestId('Username').fill('manoj.auto');
  await page.getByTestId('Password').click();
  await page.getByTestId('Password').fill('Manoj@2024');
  await page.getByTestId('Login').click();
  await page.getByTestId('todaysAppointments').getByLabel('cellmaAccordionIcon').click();
  await page.getByTestId('todaysAppointments').getByLabel('cellmaAccordionIcon').click();
  await page.getByTestId('Expand All').click();
  await page.getByTestId('Close All').click();
  await page.getByTestId('todaysAppointments').getByLabel('cellmaAccordionIcon').click();
  await page.getByTestId('todaysAppointments').getByLabel('cellmaAccordionIcon').click();
  await page.getByTestId('todaysAppointments').getByLabel('cellmaAccordionIcon').click();
  await page.getByTestId('myAlerts').getByLabel('cellmaAccordionIcon').click();
  await page.getByTestId('myAlerts').getByLabel('cellmaAccordionIcon').click();
  await page.getByRole('row', { name: 'expandRowIconundefined 790948' }).getByLabel('expandRowIconundefined').click();
  await page.getByRole('row', { name: 'expandRowIconundefined 790948' }).getByLabel('expandRowIconundefined').click();
  await page.getByTestId('myAlerts').getByLabel('cellmaAccordionIcon').click();
  await page.getByRole('button', { name: 'messages My Messages' }).getByLabel('cellmaAccordionIcon').click();
  await page.getByRole('button', { name: 'messages My Messages' }).getByLabel('cellmaAccordionIcon').click();
  await page.getByTestId('myTasks').getByLabel('cellmaAccordionIcon').click();
  await page.getByTestId('myTasks').getByLabel('cellmaAccordionIcon').click();
  await page.getByTestId('Worklist').getByLabel('cellmaAccordionIcon').click();
  await page.getByTestId('Worklist').getByLabel('cellmaAccordionIcon').click();
  await page.getByRole('button', { name: 'myCommunication Communication' }).getByLabel('cellmaAccordionIcon').click();
  await page.getByRole('button', { name: 'myCommunication Communication' }).getByLabel('cellmaAccordionIcon').click();
  await page.getByRole('button', { name: 'CaseLoad Image Avatar My' }).getByLabel('cellmaAccordionIcon').click();
  await page.getByRole('button', { name: 'CaseLoad Image Avatar My' }).getByLabel('cellmaAccordionIcon').click();
  await page.getByLabel('serviceAppointment', { exact: true }).click();
  await page.getByLabel('Back Button').click();
  await page.getByLabel('serviceMessages').click();
  await page.getByLabel('cancelIcon').click();
  await page.getByLabel('serviceTasks').click();
  await page.getByTestId('myDetails').click();
  await page.getByLabel('worklist', { exact: true }).click();
  await page.getByLabel('Back Button').click();
  await page.getByLabel('communication', { exact: true }).click();
  await page.getByLabel('Back Button').click();
  await page.getByLabel('myCaseLoad').click();
  await page.getByLabel('Back Button').click();
  await page.getByLabel('profileIcon').click();
  await page.getByLabel('Logout').click();
});